/* GENERATED by district-gen — merges geometry (ODbL) + gameplay (ours)
 * into the KYRENIA-shaped export the scene builder consumes. Swap the
 * boot import to this file to load the generated district. */
import { GEOM } from "./kyrenia-harbor-gen.geom";
import { PLAY } from "./kyrenia-harbor-gen.play";

export const KYRENIA = { ...GEOM, ...PLAY };
