"""Emit stage.

District dict -> the TypeScript files the engine loads, split for licensing
(ADR-016): geometry (OSM-derived, ODbL) and gameplay (ours) live in separate
files so share-alike never touches our design; a thin index merges them into the
`KYRENIA` export the scene builder consumes.

Outputs:
  <slug>-gen.geom.ts   bounds, waterline, buildings, palms  (ODbL, attributed)
  <slug>-gen.play.ts   everything gameplay                  (ours)
  <slug>-gen.ts        index: export const KYRENIA = {...GEOM, ...PLAY}
  <slug>-ar-candidates.json   venue -> source_id seam (NOT shipped in district)
 

Determinism: numbers formatted at fixed precision, ints as ints, no dict-order
reliance (we emit fields in a fixed order). Run under LC_ALL=C.
"""
from __future__ import annotations

import json
from typing import Any

_OSM_ATTR = "Geometry \u00a9 OpenStreetMap contributors, licensed under ODbL (opendatacommons.org/licenses/odbl)."
_OVERTURE_ATTR = "POIs \u00a9 Overture Maps Foundation, CDLA-Permissive-2.0."


def _num(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    f = float(v)
    if f.is_integer():
        return str(int(f))
    return repr(round(f, 3))


def _s(v: str | None) -> str:
    return "null" if v is None else json.dumps(v, ensure_ascii=False)


def _vec2(p: dict[str, float]) -> str:
    return "{ x: " + _num(p["x"]) + ", z: " + _num(p["z"]) + " }"


def _building(b: dict[str, Any]) -> str:
    parts = [f"x: {_num(b['x'])}", f"z: {_num(b['z'])}", f"w: {_num(b['w'])}",
             f"d: {_num(b['d'])}", f"h: {_num(b['h'])}",
             f"wall: {_s(b['wall'])}", f"roof: {_s(b['roof'])}"]
    if b.get("awning"):
        parts.append("awning: true")
    if b.get("venue"):
        parts.append(f"venue: {_s(b['venue'])}")
    return "  { " + ", ".join(parts) + " }"


def _arr(items: list[str]) -> str:
    return "[\n" + ",\n".join(items) + ",\n]" if items else "[]"


def emit_geom(d: dict[str, Any], *, use_overture: bool) -> str:
    attr = _OSM_ATTR + (("\n * " + _OVERTURE_ATTR) if use_overture else "")
    buildings = _arr([_building(b) for b in d["buildings"]])
    palms = _arr(["  " + _vec2(p) for p in d["palms"]])
    return (
        "/* GENERATED by district-gen — do not edit by hand.\n"
        f" * {attr}\n"
        " * This file is derived geometry (ODbL share-alike). Gameplay lives in the\n"
        " * .play.ts sibling and is NOT share-alike. */\n"
        'import type { BuildingSpec, Vec2 } from "./kyrenia-harbor";\n\n'
        "export const GEOM = {\n"
        f"  bounds: {{ halfW: {_num(d['bounds']['halfW'])}, halfD: {_num(d['bounds']['halfD'])} }},\n"
        f"  waterline: {_num(d['waterline'])},\n"
        f"  buildings: {buildings} as BuildingSpec[],\n"
        f"  palms: {palms} as Vec2[],\n"
        "};\n"
    )


def _venue(v: dict[str, Any]) -> str:
    return ("  { slug: " + _s(v["slug"]) + ", kind: " + _s(v["kind"])
            + ", x: " + _num(v["x"]) + ", z: " + _num(v["z"])
            + ", name: " + _s(v.get("name")) + ", nameTier: " + _s(v["name_tier"])
            + ", beerAnchor: " + _num(v["beer_anchor"])
            + ", arCandidate: " + _num(v["ar_candidate"]) + " }")


def _smash(s: dict[str, Any]) -> str:
    return ("  { x: " + _num(s["x"]) + ", z: " + _num(s["z"])
            + ", kind: " + _s(s["kind"]) + ", points: " + _num(s["points"]) + " }")


def _backdrop(b: dict[str, Any]) -> str:
    return ("  { x: " + _num(b["x"]) + ", z: " + _num(b["z"])
            + ", kind: " + _s(b["kind"]) + ", name: " + _s(b.get("name")) + " }")


def _lane(ln: dict[str, float]) -> str:
    return ("  { x0: " + _num(ln["x0"]) + ", z0: " + _num(ln["z0"])
            + ", x1: " + _num(ln["x1"]) + ", z1: " + _num(ln["z1"]) + " }")


def _zone(z: dict[str, Any]) -> str:
    return ("  { x0: " + _num(z["x0"]) + ", x1: " + _num(z["x1"])
            + ", z0: " + _num(z["z0"]) + ", z1: " + _num(z["z1"])
            + ", weight: " + _num(z["weight"]) + ", subtype: " + _s(z["subtype"]) + " }")


def _rescue(r: dict[str, Any]) -> str:
    return "  { x: " + _num(r["x"]) + ", z: " + _num(r["z"]) + ", kind: " + _num(r["kind"]) + " }"


def emit_play(d: dict[str, Any]) -> str:
    mb = d["marketBounds"]
    return (
        "/* GENERATED by district-gen — gameplay layer (ours; not ODbL). */\n"
        'import type { Vec2 } from "./kyrenia-harbor";\n\n'
        "export interface VenueSpec { slug: string; kind: string; x: number; z: number;"
        " name: string | null; nameTier: string; beerAnchor: boolean; arCandidate: boolean; }\n"
        "export interface SmashableSpec { x: number; z: number; kind: string; points: number; }\n"
        "export interface BackdropSpec { x: number; z: number; kind: string; name: string | null; }\n"
        "export interface CamelLane { x0: number; z0: number; x1: number; z1: number; }\n"
        "export interface DensityZone { x0: number; x1: number; z0: number; z1: number;"
        " weight: number; subtype: string; }\n\n"
        "export const PLAY = {\n"
        f"  marketBounds: {{ x0: {_num(mb['x0'])}, x1: {_num(mb['x1'])}, "
        f"z0: {_num(mb['z0'])}, z1: {_num(mb['z1'])} }},\n"
        f"  stallCount: {_num(d['stallCount'])},\n"
        f"  crateCount: {_num(d['crateCount'])},\n"
        f"  scooterCount: {_num(d['scooterCount'])},\n"
        f"  beerSpots: {_arr(['  ' + _vec2(p) for p in d['beerSpots']])} as Vec2[],\n"
        f"  wineHides: {_arr(['  ' + _vec2(p) for p in d['wineHides']])} as Vec2[],\n"
        f"  rescueSpots: {_arr([_rescue(r) for r in d['rescueSpots']])} as Array<Vec2 & {{ kind: number }}>,\n"
        f"  childZones: {_arr(['  ' + _vec2(p) for p in d['childZones']])} as Vec2[],\n"
        f"  cowStart: {_vec2(d['cowStart'])} as Vec2,\n"
        f"  venues: {_arr([_venue(v) for v in d['venues']])} as VenueSpec[],\n"
        f"  smashables: {_arr([_smash(s) for s in d['smashables']])} as SmashableSpec[],\n"
        f"  backdrop: {_arr([_backdrop(b) for b in d['backdrop']])} as BackdropSpec[],\n"
        f"  camelLanes: {_arr([_lane(l) for l in d['camelLanes']])} as CamelLane[],\n"
        f"  densityZones: {_arr([_zone(z) for z in d['densityZones']])} as DensityZone[],\n"
        "};\n"
    )


def emit_index(slug: str) -> str:
    return (
        "/* GENERATED by district-gen — merges geometry (ODbL) + gameplay (ours)\n"
        " * into the KYRENIA-shaped export the scene builder consumes. Swap the\n"
        " * boot import to this file to load the generated district. */\n"
        f'import {{ GEOM }} from "./{slug}-gen.geom";\n'
        f'import {{ PLAY }} from "./{slug}-gen.play";\n\n'
        "export const KYRENIA = { ...GEOM, ...PLAY };\n"
    )


def emit_ar_candidates(d: dict[str, Any]) -> str:
    cands = [{"slug": v["slug"], "source_id": v.get("source_id"), "kind": v["kind"],
              "scene": {"x": v["x"], "z": v["z"]}}
             for v in d["venues"] if v.get("ar_candidate")]
    return json.dumps({"_doc": "AR partner-venue seam (ADR-018). NOT shipped in the "
                       "district. real_coords resolved from the cached IR via source_id "
                       "only when a venue becomes a partner.",
                       "candidates": cands}, indent=2, sort_keys=True) + "\n"


def emit_attribution(*, use_overture: bool) -> str:
    lines = [_OSM_ATTR]
    if use_overture:
        lines.append(_OVERTURE_ATTR)
    return "\n".join(lines) + "\n"