"""Scene assembly + emit.

Packages everything the self-rendered-real-ground scene builder needs into one
typed TS module (KYRENIA_GEN): real sea polygons, road ribbons at true widths,
building FOOTPRINTS to extrude (not boxes), merged collider boxes for physics,
hero-landmark anchors, and the gameplay layer. This is the B-plus contract —
the box emit (emit.py) stays as the fallback path.
"""
from __future__ import annotations

import json
from typing import Any

from .project import ProjectedIR
from .render import ROAD_WIDTH, derive_sea, geom_to_coords, suggest_sea_bearing
from .simplify import DrawBuilding, SimplifiedBuilding

_HERO_KINDS = {"castle", "mosque", "landmark", "marina", "monument",
               "church_cathedral", "civilization_museum"}


def build_scene(
    pir: ProjectedIR,
    colliders: list[SimplifiedBuilding],
    draw: list[DrawBuilding],
    play: dict[str, Any],
) -> dict[str, Any]:
    sea, deviations = derive_sea(pir)
    bearing = suggest_sea_bearing(pir, sea)
    hero = [{"kind": p.kind, "x": p.point[0], "z": p.point[1], "name": p.name}
            for p in pir.pois if p.kind in _HERO_KINDS and p.name][:6]
    return {
        "bounds": pir.bounds,
        "seaBearing": bearing if bearing is not None else pir.sea_bearing_deg,
        "sea": geom_to_coords(sea),
        "roads": [{"pts": r.line, "kind": r.kind,
                   "width": ROAD_WIDTH.get(r.kind, 5.0)} for r in pir.roads],
        "buildings": [{"poly": b.footprint, "h": b.h, "wall": b.wall, "roof": b.roof}
                      for b in draw],
        "colliders": [{"x": c.x, "z": c.z, "w": c.w, "d": c.d, "h": c.h} for c in colliders],
        "landmarks": hero,
        "play": play,
        "_deviations": deviations,
    }


def emit_scene_ts(scene: dict[str, Any], slug: str, *, use_overture: bool) -> str:
    """Emit KYRENIA_GEN as a typed TS module. Data is JSON (deterministic, sorted)
    so it stays compact and diffable; the scene builder imports the typed const."""
    data = {k: v for k, v in scene.items() if k != "_deviations"}
    body = json.dumps(data, sort_keys=True, separators=(",", ":"), indent=1)
    attr = "OpenStreetMap contributors (ODbL)" + (" + Overture (CDLA-Permissive-2.0)"
                                                   if use_overture else "")
    return (
        f"/* GENERATED by district-gen — {slug}. Self-rendered real ground (Spike B-plus).\n"
        f" * Geometry \u00a9 {attr}. Sea/roads/footprints are derived geometry (ODbL). */\n"
        "export interface DrawBuilding { poly: number[][]; h: number; wall: string; roof: string; }\n"
        "export interface RoadRibbon { pts: number[][]; kind: string; width: number; }\n"
        "export interface Collider { x: number; z: number; w: number; d: number; h: number; }\n"
        "export interface Landmark { kind: string; x: number; z: number; name: string | null; }\n"
        "export interface SceneData {\n"
        "  bounds: { halfW: number; halfD: number };\n"
        "  seaBearing: number;\n"
        "  sea: number[][][];\n"
        "  roads: RoadRibbon[];\n"
        "  buildings: DrawBuilding[];\n"
        "  colliders: Collider[];\n"
        "  landmarks: Landmark[];\n"
        "  play: Record<string, unknown>;\n"
        "}\n\n"
        f"export const KYRENIA_GEN: SceneData = {body};\n"
    )
