"""Seed-SQL stage.

Emits an idempotent SQL fragment for the content layer (docs/02 §3):
region -> district -> venues. Venue slugs are IDENTICAL to those in the emitted
.ts (handoff §2), so missions can bind to venues by slug. real_coords stays NULL
— per the schema, coarse coords are added only when a venue becomes an AR partner
(ADR-018 seam), never shipped by default.
"""
from __future__ import annotations

import json
from typing import Any

# venue subtype (from poi_roles) -> venues.kind enum (bar | landmark | partner_venue)
_KIND = {"beer_anchor": "bar", "landmark": "landmark", "waterfront": "landmark"}


def _name_json(name: str | None, slug: str) -> str:
    label = name or slug.replace("-", " ").title()
    return json.dumps({"en": label, "de": label, "ru": label}, ensure_ascii=False)


def emit_seed(d: dict[str, Any], *, region_slug: str, district_slug: str,
              scene_asset_key: str) -> str:
    lines: list[str] = [
        "-- GENERATED by district-gen. Idempotent + upsert (safe to re-run after",
        "-- regenerating the cell). Run AFTER `alembic upgrade head`.",
        f"INSERT INTO regions (slug, name, active) VALUES "
        f"('{region_slug}', '{_name_json(None, region_slug)}'::jsonb, true) "
        f"ON CONFLICT (slug) DO NOTHING;",
        "",
        f"INSERT INTO districts (region_id, slug, name, scene_asset_key, spawn_template, active)",
        f"  SELECT r.id, '{district_slug}', '{_name_json(None, district_slug)}'::jsonb, "
        f"'{scene_asset_key}', '{{}}'::jsonb, true",
        f"  FROM regions r WHERE r.slug = '{region_slug}'",
        f"  ON CONFLICT (region_id, slug) DO UPDATE SET "
        f"name = EXCLUDED.name, scene_asset_key = EXCLUDED.scene_asset_key, active = true;",
        "",
    ]
    for v in sorted(d["venues"], key=lambda v: v["slug"]):
        kind = _KIND.get(v["kind"], "landmark")
        coords = json.dumps({"x": v["x"], "y": 0, "z": v["z"]})
        lines.append(
            f"INSERT INTO venues (district_id, slug, name, kind, ingame_coords)")
        lines.append(
            f"  SELECT d.id, '{v['slug']}', '{_name_json(v.get('name'), v['slug'])}'::jsonb, "
            f"'{kind}', '{coords}'::jsonb")
        lines.append(
            f"  FROM districts d WHERE d.slug = '{district_slug}' "
            f"ON CONFLICT (district_id, slug) DO UPDATE SET "
            f"name = EXCLUDED.name, kind = EXCLUDED.kind, ingame_coords = EXCLUDED.ingame_coords;")
    return "\n".join(lines) + "\n"