#!/usr/bin/env bash
# Shared/contracts is the ONLY definition of any payload.
# Regenerates both sides; CI fails on drift.
set -euo pipefail
cd "$(dirname "$0")/.."

rm -rf server/app/schemas/gen
(cd server && uv run datamodel-codegen \
  --input ../shared/contracts/api \
  --input-file-type jsonschema \
  --output app/schemas/gen \
  --output-model-type pydantic_v2.BaseModel \
  --disable-timestamp)

cat > server/app/schemas/__init__.py << 'PYEOF'
"""GENERATED contract models — regenerate via tools/codegen.sh."""
from app.schemas.gen.auth_schema import (  # noqa: F401
    AnonRequest, AnonResponse, AuthTokens, LoginRequest, RefreshRequest, SignupRequest,
)
from app.schemas.gen.consents_schema import (  # noqa: F401
    ConsentKey, ConsentSetRequest, ConsentState,
)
from app.schemas.gen.sessions_schema import (  # noqa: F401
    EndReason, EventBatch, EventType, JudgeEvent,
    SessionEndRequest, SessionEndResponse, SessionStartResponse,
)
from app.schemas.gen.me_schema import EnergyState, ProfileMe  # noqa: F401
from app.schemas.gen.leaderboards_schema import (  # noqa: F401
    LeaderboardEntry, LeaderboardResponse,
)
from app.schemas.gen.photos_schema import PhotoDecision  # noqa: F401
PYEOF

mkdir -p client/src/net/gen
node - << 'JS'
const { compileFromFile } = require("./client/node_modules/json-schema-to-typescript");
const fs = require("fs");
(async () => {
  let out = "/* GENERATED by tools/codegen.sh — DO NOT EDIT */\n";
  for (const f of ["auth", "sessions", "consents", "me", "leaderboards", "photos"]) {
    out += await compileFromFile(`shared/contracts/api/${f}.schema.json`, { bannerComment: "" });
  }
  fs.writeFileSync("client/src/net/gen/contracts.ts", out);
})();
JS
echo "codegen: OK"
